# Server configuration
server:
  port: 8088

spring:
  application:
    name: news-service

  datasource:
    url: jdbc:mysql://localhost:3306/newsservice?useSSL=false
    username: root
    password: 12042003

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        format_sql: true

jwt:
  signerKey: "QpOD7PxEqUCWRB8BU6e+Hv29TQLUuG+0sxxSJZWAPGhrVVszWZU2hT5RhoQTvhgv"

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

